### ISSUE TITLE
[Suggestion] Combiner/Dissolver recipes for NuclearCraft compounds and products

### ISSUE THREAD

**Issue by Radipon** [SmashingMods/antimatter-chemistry#144]
I think combiner recipes for these compounds would open up novel approaches to advanced NC power gen in a way that follows the theme of the pack but doesn't make them overwhelmingly broken. 

Compounds:
- Calcium Sulfate (CaSO4)
- Borax (basically Na2B4O7)

Rock Crusher products:
- Crushed Fluorite (CaF₂)
- Crushed Carobbite (KF)
- Alugentum Dust (??)
- Crushed Arsenic (As)
- Crushed Rhodochrosite (MnCO₃)
- Crushed Villiaumite (NaF)

e: dissolvables

**Comment by Radipon** [comment]
edit for rock crusher and chemical formulas

**Comment by Wishbone1977** [comment]
I don't mind using the rock crusher for the outputs it makes, particularly since the various inputs are so easy to make using Alchemistry. Still, for consistency's sake, it would make sense to be able to make them using Alchemistry as well.

However, the calcium sulfate in particular should _really_ have a Combiner recipe. There are already combiner recipes for magnesium sulfate and barium sulfate, not to mention calcium carbonate, so it seems completely illogical that calcium sulfate cannot be made that way. And the NuclearCraft way of making calcium sulfate is so _soul-crushingly_ awkward and complicated that it would really be nice to be able to skip it. In the context of the rest of the pack, it requires a stupid amount of work and resources to set up for what is a very simple end product, essentially identical to many other things the Combiner already makes.

Edit: As for borax, the only use it has is for making the radiation scrubber, and since radiation is disabled in the pack, it doesn't really matter.

**Comment by Wishbone1977** [comment]
Well, I've made Calcium Sulfate recipes for the Dissolver and Combiner now. I'm not too familiar with GitHub, and I don't even know if the author is interested in having the recipes in the pack, so I'm just going to paste the code here. If anyone wants to use them, they can just add them to their local copy of the pack.

Just add the following to the end of scripts/alchemistry.zs:

```
// NuclearCraft Calcium Sulfate
val calcium = mods.alchemistry.Util.get("calcium");
val oxygen = mods.alchemistry.Util.get("oxygen");
val calciumSulfate = <nuclearcraft:compound:0>;
Combiner.addRecipe(calciumSulfate,
[calcium,sulfur,oxygen*4]);
Dissolver.addRecipe(calciumSulfate,false,1,
[[100, calcium],
 [100, sulfur],
 [100, oxygen*4]]);
```
